# -*- coding: utf-8 -*-
"""visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMBZU0NjBqh96dm6H4yey0ZIFUcMeWWD
"""

# Создание методов визуализации

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

class Visualization:
    def plot_histogram(data, column):
        plt.show()